close all
clear


FINAL_FIGURE_subtemperateSliding
FINAL_FIGURE_sweep
FINAL_FIGURE_trajectories

SUPPLEMENT_FIGURE_functionalExperiments
SUPPLEMENT_FIGURE_subtemperateSliding_T0comparison
SUPPLEMENT_FIGURE_subtemperateSliding_tanhComparison
SUPPLEMENT_FIGURE_sweep_T0_comparison
SUPPLEMENT_FIGURE_sweep_T0_log10
